#!/bin/sh
#
#   LXC config settings for OpenWrt and NordVPN container
#
LANGUAGE=en_US.UTF-8
#export LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
#export LC_CTYPE=en_US.UTF-8

export BASEIMAGE=rootfs.tar.gz
export CONTAINER=openwrt
export CONTAINERVPN=nordvpn
export CONTAINERLOC=/var/lib/lxc/
export CONTAINERROOTFS=${CONTAINERLOC}${CONTAINER}/rootfs
export CONTAINERVPNROOTFS=${CONTAINERLOC}${CONTAINERVPN}/rootfs
export CONTAINERCONFIG=./openwrt/containerconfig
export CONTAINERVPNCONFIG=./nordvpn/containerconfig
export TZ=Europe/Amsterdam
export CONT_TYPE=docker

# Set to wanted LAN prefix
export LAN_PREFIX=192.168.56
export LAN_MASK=24
#
# OpenWrt build settings
#
export VERSION=24.10.1
#export ARCH=armsr
#export SUBARCH=armv8
#export LXCARCH=arm64
export ARCH=x86
export SUBARCH=64
export LXCARCH=amd64
export OPENWRTIMAGE=rootfs.tar.gz
export DOWNLOADNAME=openwrt-${VERSION}-${ARCH}-${SUBARCH}-${OPENWRTIMAGE}

#
# OpenWrt container settings
#
export DHCP_ENABLED=true
export LAN_DOMAIN=thuis.local
export UPSTREAM_DNS_SERVER=8.8.8.8

export OPENWRT_LOCAL_IP=${CNTNETWORKPREFIX}.49
export OPENWRT_LOCAL_GATEWAY=${CNTNETWORKPREFIX}.50
export LAN_IP6_ULA=fd00:192:168:56::1/64

export LAN_NETWORK=ow-lan
export LAN_DRIVER=macvlan
export LAN_PARENT=eth0
export LAN_SUBNET=${LAN_PREFIX}.0/${LAN_MASK}
export LAN_IP=${LAN_PREFIX}.3
export LAN_GATEWAY=${LAN_PREFIX}.3

export WAN_NETWORK=ow-wan
export WAN_DRIVER=macvlan
export WAN_PARENT=eth1

export WIFI_ENABLED=true

#WIFI_IFACES="wlan0 wlan1"
export WIFI_IFACES=wlan0
export WIFI_CHANNEL_wlan0=48
export WIFI_SSID_wlan0=TESTWIFI
export WIFI_PASSWORD_wlan0=geheimgeheim
export WIFI_BAND_wlan0=5G

export WIFI_CHANNEL_wlan1=1
export WIFI_SSID_wlan1=TESTWIFI
export WIFI_PASSWORD_wlan1=geheimgeheim
export WIFI_BAND_wlan1=2G

#!/bin/bash
export NAME=nordvpn
export NORDVPN_GROUP=nordvpn
export RUN_DIR=/run/$NAME
export SOCKET=${RUN_DIR}/nordvpnd.sock
export PID=${RUN_DIR}/nordvpnd.pid
export DAEMON=/usr/sbin/nordvpnd
export MESHROUTING="tgiesela-pyrenees.nord;tgiesela-himalayas.nord;tgiesela-atlas.nord;tgiesela-andes.nord"
export MESHLOCAL="tgiesela-pyrenees.nord;tgiesela-himalayas.nord;tgiesela-atlas.nord;tgiesela-andes.nord"
export TOKEN=e9f2abd0b04b1e549ca3e3946b93b828d42ac46113d2716870e34b2098a70a5b
export NORDVPNNICKNAME=nasvpn2
# Note CNTxxx variables will be set in Makefile
export VPN_IP=${CNTNETWORKPREFIX}.50
export CNTNETWORKIP=${CNTNETWORKPREFIX}.0
export CNTGATEWAY=${CNTNETWORKPREFIX}.1
export CNTNETWORK=${CNTNETWORKIP}/${CNTNETWORKMASKLEN}
export LOCALNETWORKS="${CNTNETWORK};${LAN_SUBNET}"

export VPNVOLUME=/dockerdata/nordvpn