config wifi-device 'radio${WIFI_RADIO}'
        option type 'mac80211'
        option phy '${WIFI_DEV}'
        option band '${WIFI_BAND}'
        option channel '${WIFI_CHANNEL}'
        option htmode 'VHT80'
	#	option htmode 'HT40'
        option disabled '0'
        option country '${COUNTRY}'

config wifi-iface 'default_radio${WIFI_RADIO}'
        option device 'radio${WIFI_RADIO}'
        option network 'lan'
        option mode 'ap'
	option ssid '${WIFI_SSID}'
	option encryption 'psk2'
	option key '${WIFI_PASSWORD}'
